Project VideoSharing {
  database_type: 'DynamoDB'
  Note: '''
    # Video sharing platform
  '''
}

Table Content {
  content_id bigint pk
  channel_id bigint
  uploaded_dttm timestamp [not null, default: `now()`]
  title varchar(64) [not null]
  description varchar(4096)
  thumbnail_link string [not null]
  views "bigint >= 0" [not null, default: 0]
  likes "bigint >= 0" [not null, default: 0]
  dislikes "bigint >= 0" [not null, default: 0]
}

enum Resolution {
  144p
  360p
  480p
  720p
  1080p
  1440p
  2160p
}

Table Video {
  video_id bigint pk
  content_id bigint
  resolution Resolution [not null]
  link string [not null]

  indexes {
    content_id
  }
}

Table Playlist {
  playlist_id bigint pk
  creator_id bigint
  name varchar(64) [not null]
  description varchar(4096)
}

Table PlaylistContent {
  playlist_id bigint
  content_id bigint

  indexes {
    playlist_id
  }
}

Table User {
  user_id bigint pk
  name varchar(64) [not null]
  avatar_link string
}

Table WatchHistory {
  user_id bigint
  content_id bigint

  indexes {
    user_id
  }
}

Table LikeHistory {
  user_id bigint
  content_id bigint
  like bool [not null, note: '`true` means user liked content, `false` means user disliked content']

  indexes {
    user_id
  }
}

Table Channel {
  channel_id bigint pk
  name varchar(64) [not null]
  description varchar(4096) [note: 'Channel description']
  subscribers "bigint >= 0" [not null, default: 0, note: 'Number of subscribers']
}

Table Subscribtion {
  user_id bigint
  channel_id bigint

  indexes {
    user_id
  }
}

Ref: Content.content_id < Video.content_id
Ref: Channel.channel_id < Content.channel_id
Ref: Channel.channel_id < Playlist.creator_id
Ref: Playlist.playlist_id < PlaylistContent.playlist_id
Ref: Content.content_id < PlaylistContent.content_id
Ref: User.user_id < WatchHistory.user_id
Ref: Content.content_id < WatchHistory.content_id
Ref: User.user_id < LikeHistory.user_id
Ref: Content.content_id < LikeHistory.content_id
Ref: User.user_id - Channel.channel_id
Ref: User.user_id < Subscribtion.user_id
Ref: Channel.channel_id < Subscribtion.channel_id
